/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TecnologiasIndexRouteImport } from './routes/tecnologias.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnologiasIndexRoute = TecnologiasIndexRouteImport.update({
  id: '/tecnologias/',
  path: '/tecnologias/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tecnologias/': typeof TecnologiasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tecnologias': typeof TecnologiasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tecnologias/': typeof TecnologiasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tecnologias/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tecnologias'
  id: '__root__' | '/' | '/tecnologias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TecnologiasIndexRoute: typeof TecnologiasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnologias/': {
      id: '/tecnologias/'
      path: '/tecnologias'
      fullPath: '/tecnologias/'
      preLoaderRoute: typeof TecnologiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TecnologiasIndexRoute: TecnologiasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
